/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author Dan40810
 */
public class ListItem extends javax.swing.JPanel
  {

    /**
     * @return the selected
     */
    public boolean isSelected()
      {
        return selected;
      }

    /**
     * @param selected the selected to set
     */
    public void setSelected(boolean selected)
      {
        this.selected = selected;
      }

    /**
     * Creates new form ListItem
     */
    
    private boolean selected;
    
    public ListItem()
      {
        initComponents();
      }

    @Override
    public void setForeground(Color color)
      {
        super.setForeground(color);
        if(lb != null)
          {
            lb.setForeground(color);
          }
      }
    
    

    public void setItem(Object obj)
      {
        if (obj instanceof Item)
          {
            Item item = (Item) obj;
            lb.setIcon(item.getIcon());
            lb.setText(item.getText());
          } else
          {
            lb.setText(obj + "");
          }
      }

    @Override
    protected void paintComponent(Graphics g)
      {
        super.paintComponent(g);
          Graphics2D g2 = (Graphics2D)g;
          g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
          if(selected)
            {
              g2.fillRect(0, 0, 5, getHeight());
              
              int x[] = {getWidth() - 10, getWidth(), getWidth()};
              int y[] = {getHeight()/2, 0, getHeight()};
              g2.fillPolygon(x, y, x.length);
            }
      }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lb = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(200, 40));
        setPreferredSize(new java.awt.Dimension(200, 40));

        lb.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lb.setText("ItemName");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb;
    // End of variables declaration//GEN-END:variables
  }
